version:          "3.4"

x-env-files:      &env-files
  env_file:
    - .env

services:
  mariadb-server-1:
    image:        mariadbclusterdocker:latest
    <<:           *env-files
    networks:
      - db-network
    restart:      always
    command:      mysqld --wsrep-new-cluster --wsrep-provider=/usr/lib/libgalera_smm.so --wsrep-recover
    ports:
      - 3306:3306
    container_name: mariadb-server-1

  mariadb-server-2:
    image:        mariadbclusterdocker:latest
    <<:           *env-files
    networks:
      - db-network
    restart:      always
    command:      mysqld --wsrep-cluster-address=gcomm://mariadb-server-1,gcomm://mariadb-server-2 --wsrep-provider=/usr/lib/libgalera_smm.so --wsrep-recover
    ports:
      - 3307:3306
    container_name: mariadb-server-2
    depends_on:
      - mariadb-server-1

  phpmyadmin:
    image:        phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mariadb-server-1
      - PMA_USER=root
      - PMA_PASSWORD=rootpass
      - MYSQL_ROOT_PASSWORD=rootpass
    networks:
      - db-network
    ports:
      - 50080:80
    restart:      always
    container_name: phpmyadmin-mariadb

networks:
  db-network:
