version:          "3.4"

x-env-files:      &env-files
  env_file:
    - .env

services:
  mariadb-server-1:
    image:        mariadbclusterdocker:10.6
    build:
      dockerfile: Dockerfile
    <<:           *env-files
    networks:
      - db-network
    restart:      unless-stopped
    command:      mysqld --wsrep-node-name=mariadb-server-1
    ports:
      - 3306:3306
    configs:
      - myconf
    volumes:
      - mariadb-server-1:/var/lib/mysql

  mariadb-server-2:
    image:        mariadbclusterdocker:10.6
    build:
      dockerfile: Dockerfile
    <<:           *env-files
    networks:
      - db-network
    restart:      unless-stopped
    command:      mysqld --wsrep-node-name=mariadb-server-2
    ports:
      - 3307:3306
    configs:
      - myconf
    volumes:
      - mariadb-server-2:/var/lib/mysql

  mariadb-server-3:
    image:        mariadbclusterdocker:10.6
    build:
      dockerfile: Dockerfile
    <<:           *env-files
    networks:
      - db-network
    restart:      unless-stopped
    command:      mysqld --wsrep-node-name=mariadb-server-3
    ports:
      - 3308:3306
    configs:
      - myconf
    volumes:
      - mariadb-server-3:/var/lib/mysql 

  phpmyadmin:
    image:        phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mariadb-server-1
      - PMA_USER=root
      - PMA_PASSWORD=rootpass
      - MYSQL_ROOT_PASSWORD=rootpass
    networks:
      - db-network
    ports:
      - 50080:80
    restart:      unless-stopped
    container_name: phpmyadmin-mariadb

configs:
  myconf:
    file: my.cnf

networks:
  db-network:

volumes:
  mariadb-server-1:
  mariadb-server-2:
  mariadb-server-3: